"""updated planet model to include order

Revision ID: c5672b3cf4c5
Revises: f07136d1f4eb
Create Date: 2022-05-04 11:42:13.063620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5672b3cf4c5'
down_revision = 'f07136d1f4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('order_from_sun', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'order_from_sun')
    # ### end Alembic commands ###
